import os
import glob

def cleanup_poc_files():
    # These patterns match the files generated by your clickjacking tester
    patterns = ["SAFE_*.html", "VULN_*.html"]
    
    deleted_count = 0
    print("--- Starting Cleanup ---")

    for pattern in patterns:
        # glob finds all files matching the pattern in the current directory
        files_to_delete = glob.glob(pattern)
        
        for file_path in files_to_delete:
            try:
                os.remove(file_path)
                print(f"[+] Deleted: {file_path}")
                deleted_count += 1
            except OSError as e:
                print(f"[-] Error deleting {file_path}: {e}")

    if deleted_count == 0:
        print("    No PoC files found to delete.")
    
    print(f"--- Cleanup Complete. Removed {deleted_count} files. ---")

if __name__ == "__main__":
    cleanup_poc_files()
